name: Run Selenium Tests
on:
  push:
    branches:
      - master # Change this to your default branch if different
  pull_request:
    branches:
      - master # Change this to your default branch if different

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java and Maven
      uses: actions/setup-java@v2
      with:
        java-version: 11 # Choose the Java version you need

    - name: Build and run Selenium tests
      run: |
        mvn clean install
        java -cp target/*:target/classes com.example.Main # Change the package and class name accordingly
      working-directory: ${{ github.workspace }}
